version: '1'
services:
  scheduler_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: scheduler
      INGRESS_HOST: 127.0.0.1
      INGRESS_PORT: 80
