version: '1'
services:
  scheduler_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: Wohn.io scheduler
      INGRESS_HOST: 127.0.0.1
      INGRESS_PORT: 80
      DB_REST_API: https://api.wohnio.weeve.engineering/devices      
      LOCATION_ID: 6238a3c87d68b786d8024bf9
      MANUFACTURER_NAME: mcclimate
      MANUFACTURER_DEVICE_TYPE: vickithermostat
      TRANSLATION_SERVICE_URL: http://localhost:8081
      EGRESS_URL: http://localhost:8082
      COMMAND_NAME: addDownlinkDeviceQueue
